version: '3.7'

services:

  prod-mode:
    container_name: web_admin_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8000:80
    environment:
      - CHOKIDAR_USEPOLLING=true 
    stdin_open: true
    networks: 
      - prod-nets

networks: 
  prod-nets: