export const RESPONSE_CONSTANT = {
  CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS:
    'CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS',
  CHANGE_STATUS_DEPARTMENT_TYPE_FAIL: 'CHANGE_STATUS_DEPARTMENT_TYPE_FAIL',
  CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
  CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
  DELETE_DEPARTMENT_TYPE_SUCCESS: 'DELETE_DEPARTMENT_TYPE_SUCCESS',
  DELETE_DEPARTMENT_TYPE_FAIL: 'DELETE_DEPARTMENT_TYPE_FAIL',
  CREATE_DEPARTMENT_TYPE_SUCCESS: 'CREATE_DEPARTMENT_TYPE_SUCCESS',
  CREATE_DEPARTMENT_TYPE_FAIL: 'CREATE_DEPARTMENT_TYPE_FAIL',
  UPDATE_DEPARTMENT_TYPE_SUCCESS: 'UPDATE_DEPARTMENT_TYPE_SUCCESS',
  UPDATE_DEPARTMENT_TYPE_FAIL: 'UPDATE_DEPARTMENT_TYPE_FAIL',
};

export const RESPONSE_MESSAGE = {
  CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS:
    'Thay đổi trạng thái loại phòng ban thành công',
  CHANGE_STATUS_DEPARTMENT_TYPE_FAIL:
    'Thay đổi trạng thái loại phòng ban thất bại',
  CHECK_CODE_SUCCESS: 'Mã loại phòng ban có thể sử dụng',
  CHECK_CODE_FAIL: 'Mã loại phòng ban đã tồn tại',
  DELETE_DEPARTMENT_TYPE_SUCCESS: 'Xoá loại phòng ban thành công',
  DELETE_DEPARTMENT_TYPE_FAIL: 'Xoá loại phòng ban thất bại',
  CREATE_DEPARTMENT_TYPE_SUCCESS: 'Tạo Mới loại phòng ban thành công',
  CREATE_DEPARTMENT_TYPE_FAIL: 'Tạo Mới loại phòng ban thất bại',
  UPDATE_DEPARTMENT_TYPE_SUCCESS: 'Cập nhật loại phòng ban thành công',
  UPDATE_DEPARTMENT_TYPE_FAIL: 'Cập nhật loại phòng ban thất bại',
};
