export enum SettingManageType {
  Title = 'CD',
  Position = 'CV',
  Group = 'NDV',
  Service = 'DV',
  DepartmentType = 'LPB',
  Department = 'PB',
  Medicine = 'MD',
  Pharmacy = 'PM',
  Faculty = 'KP',
}

export const DEFAULT_ID = '00000000-0000-0000-0000-000000000000';

export enum SettingManageKey {
  TITLE = 'TITLE',
  POSITION = 'POSITION',
  GROUP_SERVICE = 'GROUP_SERVICE',
  SERVICE = 'SERVICE',
  DEPARTMENT_TYPE = 'DEPARTMENT_TYPE',
  DEPARTMENT = 'DEPARTMENT',
  FACULTY = 'FACULTY',
}

export const SettingApiRoutes = {
  TABLE: {
    GET_ALL_TABLE: '/api/Table/all',
    CREATE_UPDATE_TABLE: '/api/Table',
  },
  MANAGE_TYPE: {
    GET_ALL_MANAGE_TYPE: '/api/ListValue/get-all-list-values',
    GET_ALL_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/get-all-list-values',
    CHECK_UNIQUE_MANAGE_TYPE: '/api/ListValue/check-code-unique',
    CHECK_UNIQUE_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/check-code-unique',
    GET_MANAGE_TYPE_BY_CODE: '/api/ListValueType/get-list-value-type',
    CHANGE_ACTIVE_MANAGE_TYPE: '/api/ListValue/change-active',
    CHANGE_ACTIVE_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/change-active',
    DELETE_MANAGE_TYPE: '/api/ListValue/delete/',
    DELETE_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/delete/',
    CREATE_MANAGE_TYPE: '/api/ListValue/add',
    CREATE_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/add',
    UPDATE_MANAGE_TYPE: '/api/ListValue/update',
    UPDATE_EXTEND_MANAGE_TYPE: '/api/ListValueExtend/update',
  },
};

export const RESPONSE_CONSTANT = {
  TABLE: {
    CREATE_TABLE_SUCCESS: 'CREATE_TABLE_SUCCESS',
    CREATE_TABLE_FAIL: 'CREATE_TABLE_FAIL',
    UPDATE_TABLE_SUCCESS: 'UPDATE_TABLE_SUCCESS',
    UPDATE_TABLE_FAIL: 'UPDATE_TABLE_FAIL',
    DELETE_TABLE_SUCCESS: 'DELETE_TABLE_SUCCESS',
    DELETE_TABLE_FAIL: 'DELETE_TABLE_FAIL',
  },
  TITLE: {
    CHANGE_STATUS_TITLE_SUCCESS: 'CHANGE_STATUS_TITLE_SUCCESS',
    CHANGE_STATUS_TITLE_FAIL: 'CHANGE_STATUS_TITLE_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_TITLE_SUCCESS: 'DELETE_TITLE_SUCCESS',
    DELETE_TITLE_FAIL: 'DELETE_TITLE_FAIL',
    CREATE_TITLE_SUCCESS: 'CREATE_TITLE_SUCCESS',
    CREATE_TITLE_FAIL: 'CREATE_TITLE_FAIL',
    UPDATE_TITLE_SUCCESS: 'UPDATE_TITLE_SUCCESS',
    UPDATE_TITLE_FAIL: 'UPDATE_TITLE_FAIL',
  },
  POSITION: {
    CHANGE_STATUS_POSITION_SUCCESS: 'CHANGE_STATUS_POSITION_SUCCESS',
    CHANGE_STATUS_POSITION_FAIL: 'CHANGE_STATUS_POSITION_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_POSITION_SUCCESS: 'DELETE_POSITION_SUCCESS',
    DELETE_POSITION_FAIL: 'DELETE_POSITION_FAIL',
    CREATE_POSITION_SUCCESS: 'CREATE_POSITION_SUCCESS',
    CREATE_POSITION_FAIL: 'CREATE_POSITION_FAIL',
    UPDATE_POSITION_SUCCESS: 'UPDATE_POSITION_SUCCESS',
    UPDATE_POSITION_FAIL: 'UPDATE_POSITION_FAIL',
  },
  GROUP_SERVICE: {
    CHANGE_STATUS_GROUP_SERVICE_SUCCESS: 'CHANGE_STATUS_GROUP_SERVICE_SUCCESS',
    CHANGE_STATUS_GROUP_SERVICE_FAIL: 'CHANGE_STATUS_GROUP_SERVICE_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_GROUP_SERVICE_SUCCESS: 'DELETE_GROUP_SERVICE_SUCCESS',
    DELETE_GROUP_SERVICE_FAIL: 'DELETE_GROUP_SERVICE_FAIL',
    CREATE_GROUP_SERVICE_SUCCESS: 'CREATE_GROUP_SERVICE_SUCCESS',
    CREATE_GROUP_SERVICE_FAIL: 'CREATE_GROUP_SERVICE_FAIL',
    UPDATE_GROUP_SERVICE_SUCCESS: 'UPDATE_GROUP_SERVICE_SUCCESS',
    UPDATE_GROUP_SERVICE_FAIL: 'UPDATE_GROUP_SERVICE_FAIL',
  },
  SERVICE: {
    CHANGE_STATUS_SERVICE_SUCCESS: 'CHANGE_STATUS_SERVICE_SUCCESS',
    CHANGE_STATUS_SERVICE_FAIL: 'CHANGE_STATUS_SERVICE_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
    DELETE_SERVICE_FAIL: 'DELETE_SERVICE_FAIL',
    CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
    CREATE_SERVICE_FAIL: 'CREATE_SERVICE_FAIL',
    UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
    UPDATE_SERVICE_FAIL: 'UPDATE_SERVICE_FAIL',
  },
  DEPARTMENT_TYPE: {
    CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS:
      'CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS',
    CHANGE_STATUS_DEPARTMENT_TYPE_FAIL: 'CHANGE_STATUS_DEPARTMENT_TYPE_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_DEPARTMENT_TYPE_SUCCESS: 'DELETE_DEPARTMENT_TYPE_SUCCESS',
    DELETE_DEPARTMENT_TYPE_FAIL: 'DELETE_DEPARTMENT_TYPE_FAIL',
    CREATE_DEPARTMENT_TYPE_SUCCESS: 'CREATE_DEPARTMENT_TYPE_SUCCESS',
    CREATE_DEPARTMENT_TYPE_FAIL: 'CREATE_DEPARTMENT_TYPE_FAIL',
    UPDATE_DEPARTMENT_TYPE_SUCCESS: 'UPDATE_DEPARTMENT_TYPE_SUCCESS',
    UPDATE_DEPARTMENT_TYPE_FAIL: 'UPDATE_DEPARTMENT_TYPE_FAIL',
  },
  DEPARTMENT: {
    CHANGE_STATUS_DEPARTMENT_SUCCESS: 'CHANGE_STATUS_DEPARTMENT_SUCCESS',
    CHANGE_STATUS_DEPARTMENT_FAIL: 'CHANGE_STATUS_DEPARTMENT_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS',
    DELETE_DEPARTMENT_FAIL: 'DELETE_DEPARTMENT_FAIL',
    CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
    CREATE_DEPARTMENT_FAIL: 'CREATE_DEPARTMENT_FAIL',
    UPDATE_DEPARTMENT_SUCCESS: 'UPDATE_DEPARTMENT_SUCCESS',
    UPDATE_DEPARTMENT_FAIL: 'UPDATE_DEPARTMENT_TYPE_FAIL',
  },
  FACULTY: {
    CHANGE_STATUS_FACULTY_SUCCESS: 'CHANGE_STATUS_FACULTY_SUCCESS',
    CHANGE_STATUS_FACULTY_FAIL: 'CHANGE_STATUS_FACULTY_FAIL',
    CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
    CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
    DELETE_FACULTY_SUCCESS: 'DELETE_FACULTY_SUCCESS',
    DELETE_FACULTY_FAIL: 'DELETE_FACULTY_FAIL',
    CREATE_FACULTY_SUCCESS: 'CREATE_FACULTY_SUCCESS',
    CREATE_FACULTY_FAIL: 'CREATE_FACULTY_FAIL',
    UPDATE_FACULTY_SUCCESS: 'UPDATE_FACULTY_SUCCESS',
    UPDATE_FACULTY_FAIL: 'UPDATE_FACULTY_TYPE_FAIL',
  },
};

export const RESPONSE_MESSAGE = {
  TABLE: {
    CREATE_TABLE_SUCCESS: 'Tạo Mới Thông Tin Bàn Tiếp Nhận Thành Công',
    CREATE_TABLE_FAIL: 'Tạo Mới Thông Tin Bàn Tiếp Nhận Thất Bại',
    UPDATE_TABLE_SUCCESS: 'Cập Nhật Thông Tin Bàn Tiếp Nhận Thành Công',
    UPDATE_TABLE_FAIL: 'Cập Nhật Thông Tin Bàn Tiếp Nhận Thất Bại',
    DELETE_TABLE_SUCCESS: 'Xoá Thông Tin Bàn Tiếp Nhận Thành Công',
    DELETE_TABLE_FAIL: 'Xoá Thông Tin Bàn Tiếp Nhận Thất Bại',
  },
  TITLE: {
    CHANGE_STATUS_TITLE_SUCCESS: 'Thay Đổi Trạng Thái Chức Danh Thành Công',
    CHANGE_STATUS_TITLE_FAIL: 'Thay Đổi Trạng Thái Chức Danh Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Chức Danh Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Chức Danh Đã Tồn Tại',
    DELETE_TITLE_SUCCESS: 'Xoá Chức Danh Thành Công',
    DELETE_TITLE_FAIL: 'Xoá Chức Danh Thất Bại',
    CREATE_TITLE_SUCCESS: 'Tạo Mới Chức Danh Thành Công',
    CREATE_TITLE_FAIL: 'Tạo Mới Chức Danh Thất Bại',
    UPDATE_TITLE_SUCCESS: 'Cập Nhật Chức Danh Thành Công',
    UPDATE_TITLE_FAIL: 'Cập Nhật Chức Danh Thất Bại',
  },
  POSITION: {
    CHANGE_STATUS_POSITION_SUCCESS: 'Thay Đổi Trạng Thái Chức Vụ Thành Công',
    CHANGE_STATUS_POSITION_FAIL: 'Thay Đổi Trạng Thái Chức Vụ Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Chức Vụ Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Chức Vụ Đã Tồn Tại',
    DELETE_POSITION_SUCCESS: 'Xoá Chức Vụ Thành Công',
    DELETE_POSITION_FAIL: 'Xoá Chức Vụ Thất Bại',
    CREATE_POSITION_SUCCESS: 'Tạo Mới Chức Vụ Thành Công',
    CREATE_POSITION_FAIL: 'Tạo Mới Chức Vụ Thất Bại',
    UPDATE_POSITION_SUCCESS: 'Cập Nhật Chức Vụ Thành Công',
    UPDATE_POSITION_FAIL: 'Cập Nhật Chức Vụ Thất Bại',
  },
  GROUP_SERVICE: {
    CHANGE_STATUS_GROUP_SERVICE_SUCCESS:
      'Thay Đổi Trạng Thái Nhóm Dịch Vụ Thành Công',
    CHANGE_STATUS_GROUP_SERVICE_FAIL:
      'Thay Đổi Trạng Thái Nhóm Dịch Vụ Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Nhóm Dịch Vụ Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Nhóm Dịch Vụ Đã Tồn Tại',
    DELETE_GROUP_SERVICE_SUCCESS: 'Xoá Nhóm Dịch Vụ Thành Công',
    DELETE_GROUP_SERVICE_FAIL: 'Xoá Nhóm Dịch Vụ Thất Bại',
    CREATE_GROUP_SERVICE_SUCCESS: 'Tạo Mới Nhóm Dịch Vụ Thành Công',
    CREATE_GROUP_SERVICE_FAIL: 'Tạo Mới Nhóm Dịch Vụ Thất Bại',
    UPDATE_GROUP_SERVICE_SUCCESS: 'Cập Nhật Nhóm Dịch Vụ Thành Công',
    UPDATE_GROUP_SERVICE_FAIL: 'Cập Nhật Nhóm Dịch Vụ Thất Bại',
  },
  SERVICE: {
    CHANGE_STATUS_SERVICE_SUCCESS: 'Thay Đổi Trạng Thái Dịch Vụ Thành Công',
    CHANGE_STATUS_SERVICE_FAIL: 'Thay Đổi Trạng Thái Dịch Vụ Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Dịch Vụ Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Dịch Vụ Đã Tồn Tại',
    DELETE_SERVICE_SUCCESS: 'Xoá Dịch Vụ Thành Công',
    DELETE_SERVICE_FAIL: 'Xoá Dịch Vụ Thất Bại',
    CREATE_SERVICE_SUCCESS: 'Tạo Mới Dịch Vụ Thành Công',
    CREATE_SERVICE_FAIL: 'Tạo Mới Dịch Vụ Thất Bại',
    UPDATE_SERVICE_SUCCESS: 'Cập Nhật Dịch Vụ Thành Công',
    UPDATE_SERVICE_FAIL: 'Cập Nhật Dịch Vụ Thất Bại',
  },
  DEPARTMENT_TYPE: {
    CHANGE_STATUS_DEPARTMENT_TYPE_SUCCESS:
      'Thay Đổi Trạng Thái Loại Phòng Ban Thành Công',
    CHANGE_STATUS_DEPARTMENT_TYPE_FAIL:
      'Thay Đổi Trạng Thái Loại Phòng Ban Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Loại Phòng Ban Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Loại Phòng Ban Đã Tồn Tại',
    DELETE_DEPARTMENT_TYPE_SUCCESS: 'Xoá Loại Phòng Ban Thành Công',
    DELETE_DEPARTMENT_TYPE_FAIL: 'Xoá Loại Phòng Ban Thất Bại',
    CREATE_DEPARTMENT_TYPE_SUCCESS: 'Tạo Mới Loại Phòng Ban Thành Công',
    CREATE_DEPARTMENT_TYPE_FAIL: 'Tạo Mới Loại Phòng Ban Thất Bại',
    UPDATE_DEPARTMENT_TYPE_SUCCESS: 'Cập Nhật Loại Phòng Ban Thành Công',
    UPDATE_DEPARTMENT_TYPE_FAIL: 'Cập Nhật Loại Phòng Ban Thất Bại',
  },
  DEPARTMENT: {
    CHANGE_STATUS_DEPARTMENT_SUCCESS:
      'Thay Đổi Trạng Thái Phòng Ban Thành Công',
    CHANGE_STATUS_DEPARTMENT_FAIL: 'Thay Đổi Trạng Thái Phòng Ban Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Phòng Ban Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Phòng Ban Đã Tồn Tại',
    DELETE_DEPARTMENT_SUCCESS: 'Xoá Phòng Ban Thành Công',
    DELETE_DEPARTMENT_FAIL: 'Xoá Phòng Ban Thất Bại',
    CREATE_DEPARTMENT_SUCCESS: 'Tạo Mới Phòng Ban Thành Công',
    CREATE_DEPARTMENT_FAIL: 'Tạo Mới Phòng Ban Thất Bại',
    UPDATE_DEPARTMENT_SUCCESS: 'Cập Nhật Phòng Ban Thành Công',
    UPDATE_DEPARTMENT_FAIL: 'Cập Nhật Phòng Ban Thất Bại',
  },
  FACULTY: {
    CHANGE_STATUS_FACULTY_SUCCESS: 'Thay Đổi Trạng Thái Khoa Thành Công',
    CHANGE_STATUS_FACULTY_FAIL: 'Thay Đổi Trạng Thái Khoa Thất Bại',
    CHECK_CODE_SUCCESS: 'Mã Khoa Có Thể Sử Dụng',
    CHECK_CODE_FAIL: 'Mã Khoa Đã Tồn Tại',
    DELETE_FACULTY_SUCCESS: 'Xoá Khoa Thành Công',
    DELETE_FACULTY_FAIL: 'Xoá Khoa Thất Bại',
    CREATE_FACULTY_SUCCESS: 'Tạo Mới Khoa Thành Công',
    CREATE_FACULTY_FAIL: 'Tạo Mới Khoa Thất Bại',
    UPDATE_FACULTY_SUCCESS: 'Cập Nhật Khoa Thành Công',
    UPDATE_FACULTY_FAIL: 'Cập Nhật Khoa Thất Bại',
  },
};

export const tableRole: any[] = [
  { id: 'no', label: '#', minWidth: 50 },
  { id: 'code', label: 'Mã', minWidth: 120 },
  { id: 'name', label: 'Tên', minWidth: 120 },
  { id: 'description', label: 'Mô tả', minWidth: 120 },
  { id: 'is_active', label: 'Trạng thái', minWidth: 120 },
  { id: 'actions', label: 'Chức năng', minWidth: 170 },
];

export const tablePermissionInRole: any[] = [
  { id: 'no', label: '#', minWidth: 50 },
  { id: 'code', label: 'Mã', minWidth: 120 },
  { id: 'description', label: 'Mô tả', minWidth: 120 },
  { id: 'is_active', label: 'Trạng thái', minWidth: 120 },
  { id: 'actions', label: 'Có Thể  Truy Cập', minWidth: 200 },
];

export const tableUserInRole: any[] = [
  { id: 'no', label: '#', minWidth: 50 },
  { id: 'user_name', label: 'Tên đăng nhập', minWidth: 120 },
  { id: 'code', label: 'Mã nhân viên', minWidth: 120 },
  { id: 'name', label: 'Tên nhân viên', minWidth: 120 },
  { id: 'is_active', label: 'Trạng thái', minWidth: 120 },
  { id: 'actions', label: 'Có Thể  Truy Cập', minWidth: 200 },
];

export const tableValue: any[] = [
  { id: 'no', label: '#', minWidth: 50 },
  { id: 'code', label: 'Mã', minWidth: 120 },
  { id: 'description', label: 'Tên', minWidth: 120 },
  { id: 'type', label: 'Loại', minWidth: 120 },
  { id: 'actions', label: 'Chức năng', minWidth: 170 },
];
