export const RESPONSE_CONSTANT = {
  CHANGE_STATUS_DEPARTMENT_SUCCESS: 'CHANGE_STATUS_DEPARTMENT_SUCCESS',
  CHANGE_STATUS_DEPARTMENT_FAIL: 'CHANGE_STATUS_DEPARTMENT_FAIL',
  CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
  CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
  DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS',
  DELETE_DEPARTMENT_FAIL: 'DELETE_DEPARTMENT_FAIL',
  CREATE_DEPARTMENT_SUCCESS: 'CREATE_DEPARTMENT_SUCCESS',
  CREATE_DEPARTMENT_FAIL: 'CREATE_DEPARTMENT_FAIL',
  UPDATE_DEPARTMENT_SUCCESS: 'UPDATE_DEPARTMENT_SUCCESS',
  UPDATE_DEPARTMENT_FAIL: 'UPDATE_DEPARTMENT_TYPE_FAIL',
};

export const RESPONSE_MESSAGE = {
  CHANGE_STATUS_DEPARTMENT_SUCCESS: 'Thay đổi trạng thái phòng ban thành công',
  CHANGE_STATUS_DEPARTMENT_FAIL: 'Thay đổi trạng thái phòng ban thất bại',
  CHECK_CODE_SUCCESS: 'Mã phòng ban Có Thể Sử Dụng',
  CHECK_CODE_FAIL: 'Mã phòng ban Đã Tồn Tại',
  DELETE_DEPARTMENT_SUCCESS: 'Xoá phòng ban thành công',
  DELETE_DEPARTMENT_FAIL: 'Xoá phòng ban thất bại',
  CREATE_DEPARTMENT_SUCCESS: 'Tạo mới phòng ban thành công',
  CREATE_DEPARTMENT_FAIL: 'Tạo mới phòng ban thất bại',
  UPDATE_DEPARTMENT_SUCCESS: 'Cập nhật phòng ban thành công',
  UPDATE_DEPARTMENT_FAIL: 'Cập nhật phòng ban thất bại',
};
