export const RESPONSE_CONSTANT = {
  CHANGE_STATUS_SERVICE_SUCCESS: 'CHANGE_STATUS_SERVICE_SUCCESS',
  CHANGE_STATUS_SERVICE_FAIL: 'CHANGE_STATUS_SERVICE_FAIL',
  CHECK_CODE_SUCCESS: 'CHECK_CODE_SUCCESS',
  CHECK_CODE_FAIL: 'CHECK_CODE_FAIL',
  DELETE_SERVICE_SUCCESS: 'DELETE_SERVICE_SUCCESS',
  DELETE_SERVICE_FAIL: 'DELETE_SERVICE_FAIL',
  CREATE_SERVICE_SUCCESS: 'CREATE_SERVICE_SUCCESS',
  CREATE_SERVICE_FAIL: 'CREATE_SERVICE_FAIL',
  UPDATE_SERVICE_SUCCESS: 'UPDATE_SERVICE_SUCCESS',
  UPDATE_SERVICE_FAIL: 'UPDATE_SERVICE_FAIL',
};

export const RESPONSE_MESSAGE = {
  CHANGE_STATUS_SERVICE_SUCCESS: 'Thay Đổi trạng thái dịch vụ thành công',
  CHANGE_STATUS_SERVICE_FAIL: 'Thay Đổi trạng thái dịch vụ thất bại',
  CHECK_CODE_SUCCESS: 'Mã dịch vụ có thể sử dụng',
  CHECK_CODE_FAIL: 'Mã dịch vụ đã tồn tại',
  DELETE_SERVICE_SUCCESS: 'Xoá dịch vụ thành công',
  DELETE_SERVICE_FAIL: 'Xoá dịch vụ thất bại',
  CREATE_SERVICE_SUCCESS: 'Tạo mới dịch vụ thành công',
  CREATE_SERVICE_FAIL: 'Tạo mới dịch vụ thất bại',
  UPDATE_SERVICE_SUCCESS: 'Cập nhật dịch vụ thành công',
  UPDATE_SERVICE_FAIL: 'Cập nhật dịch vụ thất bại',
};
